pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Trigger CodeQL in GitHub Action') {
            steps {
                script {
                    // Use the existing 'Username with password' credential
                    withCredentials([usernamePassword(credentialsId: '3777c30a-0948-46fe-9901-ed688e8ca8d6', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
                        sh """
                        curl -X POST \
                        -H "Accept: application/vnd.github.v3+json" \
                        -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                        https://api.github.com/repos/claireelyse/jenkins/actions/workflows/codeql-analysis.yml/dispatches \
                        -d '{"ref":"main"}'
                        """
                    }
                }
            }
        }
    }
}
