pipeline {
    agent any

    stages {
        stage('Approval Gate') {
            steps {
                // Timeout block for the input step
                timeout(time: 10, unit: 'MINUTES') {  // Waits for 10 minutes for approval
                    // Manual approval step
                    input message: 'Do you approve deployment?', ok: 'Deploy', submitter: 'admin'
                }
            }
        }
        stage('Quality Gate') {
            steps {
                script {
                    // Use the existing 'Username with password' credential
                    withCredentials([usernamePassword(credentialsId: '3777c30a-0948-46fe-9901-ed688e8ca8d6', usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
                        sh """
                        curl -X POST \
                        -H "Accept: application/vnd.github.v3+json" \
                        -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                        https://api.github.com/repos/claireelyse/jenkins/actions/workflows/codeql-analysis.yml/dispatches \
                        -d '{"ref":"main"}'
                        """
                    }
                }
            }
        }
        post {
            // Fail the job if the input timeout is reached
            aborted {
                echo 'Approval was not granted in time. Failing the job.'
                error('Job failed due to lack of approval.')
            }
        }
    }
}
