pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
        stage('Trigger CodeQL in GitHub Action') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github-token', variable: 'JENKINS')]) {
                        def response = httpRequest acceptType: 'APPLICATION_JSON',
                            consoleLogResponseBody: true,
                            customHeaders: [[name: 'Authorization', value: "Bearer ${JENKINS}"]],
                            url: 'https://api.github.com/repos/claireelyse/jenkins/actions/workflows/codeql-analysis.yml/dispatches',
                            validResponseCodes: '204',
                            requestBody: '{"ref":"main"}'
                        
                        if (response.status != 204) {
                            error "Failed to trigger GitHub Action"
                        } else {
                            echo "GitHub Action triggered successfully."
                        }
                    }
                }
            }
        }
    }

